# Generated by Django 6.0.6 on 2026-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('jedzenie', 'Jedzenie'), ('transport', 'Transport'), ('mieszkanie', 'Mieszkanie'), ('rozrywka', 'Rozrywka'), ('zdrowie', 'Zdrowie'), ('inne', 'Inne')], max_length=20, verbose_name='Kategoria')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota (zł)')),
                ('data', models.DateField(verbose_name='Data')),
                ('opis', models.CharField(blank=True, max_length=200, verbose_name='Opis (opcjonalnie)')),
            ],
            options={
                'verbose_name': 'Wydatek',
                'verbose_name_plural': 'Wydatki',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
